version: "3"
services:
    caddy2:
        build: 
            context: .
        container_name: caddy2
        deploy:
            restart_policy:
                condition: any
        environment:
            AWS_ACCESS_KEY_ID: "(set in docker-compose.override.yaml)"
            AWS_SECRET_ACCESS_KEY: "(set in docker-compose.override.yaml)"
        volumes:
            - './data/:/data'
            - './config/:/config'
            - './Caddyfile:/etc/caddy/Caddyfile'
            - './sites/:/etc/caddy/sites/'
            - './logs/:/logs/'
            - './aws_creds:'
        ports:
            - '55080:80'
            - '55443:443'
        restart: always
